#!/bin/bash

rm -rf docs
rm -rf generated
rm -rf node_modules

docker stop swagger-generator
docker stop swagger-editor
docker stop swagger-ui

docker rm swagger-generator
docker rm swagger-editor
docker rm swagger-ui

