#!/bin/bash

# Generated Sandboxes Packages
rm -rf generated

# Node.JS Dependencies
rm -rf node_modules

# Remove Docker Swagger Tools
docker stop swagger-editor
docker stop swagger-ui
docker stop swagger-generator
docker stop nodejs-server
docker stop spring-server

docker rm swagger-editor
docker rm swagger-ui
docker rm swagger-generator
docker rm nodejs-server
docker rm spring-server

