#!/usr/bin/env node

const config = require('./config.json');
const tools = require('./lib/common.js').tools;
const swg = require('./lib/swgrequest.js');
const fs = require('fs-extra');
const path = require('path');

const spec = fs.readJsonSync(path.resolve('./specs/users_api.json'));

// Criando as apis na versão server
tools.shell.echo(swg.createServer(spec, 'spring'));
tools.shell.echo(swg.createServer(spec, 'nodejs-server'));

// Criando os apis na versão client
tools.shell.echo(swg.createClient(spec, 'java'));
tools.shell.echo(swg.createClient(spec, 'javascript'));

