#!/usr/bin/env node

const tools = require('./lib/common.js').tools;
const build = require('./lib/builders.js');
const path = require('path');
const config = require('./config.json');

const backdir = path.resolve(__dirname);
build.clients(backdir)
  .then((result) => {
    console.log(result);
  });

build.servers(backdir)
  .then((result) => {
    console.log(result);
  });
