#!/usr/bin/env node

const path = require('path');
const tools = require('./lib/common.js').tools;
const config = require('./config.json');

// copy spring Dockerfile to spring-server
let source = path.resolve(__dirname, './templates/docker/spring/Dockerfile');
let target = path.resolve(`${config.generator.generated}/spring-server/Dockerfile`);
tools.shell.cp(source, target);

// copy nodejs Dockerfile to node-server-server
source = path.resolve(__dirname, './templates/docker/node/Dockerfile');
target = path.resolve(`${config.generator.generated}/nodejs-server-server/Dockerfile`);
tools.shell.cp(source, target);

// copy nodejs-server templates
source = path.resolve(__dirname, './templates/nodejs-server-server/service/UserService.js');
target = path.resolve(`${config.generator.generated}/nodejs-server-server/service/UserService.js`);
tools.shell.cp(source, target);

// copy spring-server templates
source = path.resolve(__dirname, './templates/spring-server/src/main/java/api/UsersApi.java');
target = path.resolve(`${config.generator.generated}/spring-server/src/main/java/api/UsersApi.java`);
tools.shell.cp(source, target);
