#!/usr/bin/env node

const tools = require('./lib/common.js').tools;
const build = require('./lib/builders.js');
const asciify = require('asciify');

build.dockerServers()
.then((result) => {
  tools.shell.echo(result);
});

asciify('Step 5', {font:'small'}, (err, res) => {tools.shell.echo(res)});
asciify('Dockerize APIs', {font:'standard', color: 'blue'}, (err, res) => {tools.shell.echo(res)});

