#!/bin/bash

mkdir specs
curl https://raw.githubusercontent.com/gft-technical-practices/workshop-api-development/master/users_api.yaml --output ./specs/users_api.yaml

# Installing npm modules
npm install shelljs commander yamljs request request-promise fs-extra lodash handlebars unzipper

# The easiest way to run Swagger tools is to use docker containers
docker pull swaggerapi/swagger-generator
docker pull swaggerapi/swagger-editor
docker pull swaggerapi/swagger-ui

# APIs base docker images
docker pull node:alpine
docker pull openjdk:8-jdk-alpine

# Another comand line tool
sudo -i npm install -g swagger yamljs mustache

# Run containers
docker run -d -e GENERATOR_HOST=http://localhost -p 9000:8080 --name swagger-generator swaggerapi/swagger-generator
docker run -d -p 8000:8080 --name swagger-editor swaggerapi/swagger-editor
docker run -d -p 7000:8080 --name swagger-ui swaggerapi/swagger-ui

# List running containers
docker ps

# Convert YAML Swagger to JSON Swagger
yaml2json ./specs/users_api.yaml --pretty  > ./specs/users_api.json
